# Streamlit Secrets Configuration Template
# IMPORTANT: 
# 1. Copy this file to .streamlit/secrets.toml
# 2. Replace with your actual API keys
# 3. NEVER commit secrets.toml to version control
# 4. Add .streamlit/secrets.toml to .gitignore
# 5. For Streamlit Cloud, add these in the dashboard instead

# ============================================
# API KEYS
# ============================================

[api_keys]
# REQUIRED: Serper API key for SERP analysis
# Get your free key at https://serper.dev (2,500 queries/month free)
serper_key = "your-serper-api-key-here"

# OPTIONAL: OpenAI API key for AI-powered recommendations
# Get your key at https://platform.openai.com/api-keys
openai_key = "sk-your-openai-api-key-here"

# OPTIONAL: Anthropic API key for Claude AI recommendations
# Get your key at https://console.anthropic.com/
anthropic_key = "sk-ant-your-anthropic-api-key-here"

# OPTIONAL: Google AI API key for Gemini recommendations
# Get your key at https://makersuite.google.com/app/apikey
google_key = "your-google-ai-api-key-here"

# ============================================
# APPLICATION CONFIGURATION
# ============================================

[app_config]
# Maximum number of queries to analyze for SERP overlap
max_serp_queries = 50

# Default semantic similarity threshold (0.0 to 1.0)
default_similarity_threshold = 0.8

# Default keyword overlap threshold (percentage)
default_overlap_threshold = 10

# Enable debug mode (shows additional information)
debug_mode = false

# ============================================
# RATE LIMITING CONFIGURATION
# ============================================

[rate_limits]
# Serper API rate limiting
serper_requests_per_second = 10
serper_batch_size = 10
delay_between_batches = 1

# General API rate limiting
max_concurrent_requests = 5
request_timeout = 30

# ============================================
# ADVANCED SETTINGS
# ============================================

[advanced]
# Cache TTL in seconds (how long to cache API results)
cache_ttl = 3600

# Maximum file size for uploads (in MB)
max_file_size = 100

# Enable experimental features
enable_experimental = false

# Logging level (DEBUG, INFO, WARNING, ERROR)
log_level = "INFO"

# ============================================
# SERP ANALYSIS SETTINGS
# ============================================

[serp_settings]
# Number of results to fetch per query
results_per_query = 10

# Country code for SERP results
country_code = "us"

# Language for SERP results
language = "en"

# Include paid results in analysis
include_paid = false

# ============================================
# AI MODEL SETTINGS
# ============================================

[ai_settings]
# Default AI provider (OpenAI, Anthropic, Google, or None)
default_provider = "None"

# Default models for each provider
openai_model = "gpt-4"
anthropic_model = "claude-3-opus-20240229"
google_model = "gemini-pro"

# Maximum tokens for AI responses
max_tokens = 1000

# Temperature for AI responses (0.0 to 1.0)
temperature = 0.7

# ============================================
# EXPORT SETTINGS
# ============================================

[export]
# Default export format (markdown, excel, csv, json)
default_format = "markdown"

# Include raw data in exports
include_raw_data = false

# Compress large exports
compress_exports = true

# ============================================
# SECURITY SETTINGS
# ============================================

[security]
# Require authentication for app access (Streamlit Cloud only)
require_auth = false

# Allowed email domains for access (if auth enabled)
allowed_domains = ["example.com"]

# Session timeout in minutes
session_timeout = 60

# ============================================
# MONITORING & ANALYTICS
# ============================================

[monitoring]
# Enable usage analytics
enable_analytics = false

# Analytics endpoint (if custom analytics)
analytics_endpoint = ""

# Track API usage
track_api_usage = true

# ============================================
# NOTES FOR DEPLOYMENT
# ============================================

# For Streamlit Cloud deployment:
# 1. Don't include this file in your repository
# 2. Add secrets via Streamlit Cloud dashboard
# 3. Go to App Settings > Secrets
# 4. Copy and paste the relevant sections

# For local development:
# 1. Copy this file to .streamlit/secrets.toml
# 2. Fill in your actual API keys
# 3. Run: streamlit run app.py

# For production deployment:
# 1. Use environment variables or secret management service
# 2. Never hardcode API keys in your code
# 3. Rotate keys regularly for security
